name: BUILD_AND_PUSH_IMAGE
  
on:
  push:
    tags:        
      - v*   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build --rm --tag rcndev/keeper-bots:${{steps.get_version.outputs.VERSION}} -f docker/Dockerfile .
      - name: Push the tagged Docker image
        run: docker push rcndev/keeper-bots:${{steps.get_version.outputs.VERSION}}
